server:
  port: 9010

spring:
  application:
    name: TheLife-Server-Jobsearch
  # 多环境配置：当前环境
  profiles:
    active: dev

  #redis配置
  redis:
    #数据库索引
    database: 0
    host: 121.4.67.77
    port: 6379
    #password:
    password: yuyue520
    #连接超时时间
    timeout: 5000

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6000/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,页面会显示主机名
    preferIpAddress: true     #访问路径可以显示IP地址

#是否开启 swagger-ui
swagger:
  enabled: true


#最大连接数
http:
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
  #关闭池中的空闲连接-等待时间(毫秒)
  waitTime: 30000
  #关闭池中的空闲连接-空闲时间(分钟)
  idleConTime: 3