server:
  port: 9000

spring:
  application:
    name: TheLife-Server-About
  profiles:
    active: dev

  #redis配置
  redis:
    #数据库索引
    database: 0
    host: 47.104.107.189
    port: 6379
    #password:
    password: yuyue520
    #连接超时时间
    timeout: 5000

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:7000/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,页面会显示主机名
    preferIpAddress: true     #访问路径可以显示IP地址

feign:
  hystrix:
    enabled: true # 开启服务熔断器

#Hystrix有隔离策略：SEMAPHORE 防止向其他服务传递token获取不到请求对象RequestContextHolder
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE #Hystrix有隔离策略：THREAD（默认）以及SEMAPHORE，THREAD时使用该隔离策略防止RequestContextHolder对象中不可用（隔离策略为THREAD时是没办法拿到ThreadLocal中的值）

#是否开启 swagger-ui
swagger:
  enabled: true