server:
  port: 7000

spring:
  application:
    name: TheLife-Eureka

  #redis配置
  redis:
    #数据库索引
    database: 0
    host: 47.104.107.189
    port: 6379
    #password:
    password: yuyue520
    #连接超时时间
    timeout: 5000

eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称
  client:
    registerWithEureka: false # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: false # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:    # Eureka客户端与Eureka服务端的交互地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#是否开启 swagger-ui
swagger:
  enabled: true